name = "unirepsocial"
type = "javascript"
account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-02-16"

[site]
bucket = "build"
entry-point = "dist"

[build]
command = "yarn build:worker && echo '{\"name\": \"unirepsocial\",\"main\":\"index.js\"}' > dist/package.json"

[build.upload]
format = "service-worker"
